#copied verbatim from osmdata 

language: r
warnings_are_errors: true
sudo: required
cache: packages
#group: edge # https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2

env:
matrix:
    include:
        - os: linux
          r: release
          dist: trusty
        - os: linux
          r: oldrel
          dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
    - devtools
r_github_packages:
    - jimhester/covr

after_success:
    - Rscript -e "covr::codecov(line_exclusions = list('src/rapidxml.h','src/rapidxml_print.h'))"
